-- ====================================
--SALES ANALYSIS
-- ====================================


--TOTAL REVENUE
SELECT SUM(PAYMENT_VALUE) AS TOTAL_REVENUE
FROM PAYMENTS;


--TOTAL ORDERS
SELECT COUNT(*) AS TOTAL_ORDERS 
FROM ORDERS;


--AVG ORDER VALUE
SELECT AVG(ORDER_TOTAL) AS AVG_ORDER_TOTAL FROM 
                        (SELECT ORDER_ID, SUM(PRICE)AS ORDER_TOTAL
                                FROM ORDER_ITEMS GROUP BY ORDER_ID) AS TEMP;


--MONTHLY REVENUE TREND
SELECT DATE_FORMAT(O.ORDER_PURCHASE_TIMESTAMP, "%Y-%m") AS MONTH, SUM(P.PAYMENT_VALUE) AS MONTHLY_REVENUE
FROM ORDERS AS O
JOIN PAYMENTS AS P
ON O.ORDER_ID=P.ORDER_ID
GROUP BY MONTH
ORDER BY MONTH;


--MONTHLY ORDER TREND
SELECT DATE_FORMAT(ORDER_PURCHASE_TIMESTAMP, '%Y-%m') AS MONTH,COUNT(*) AS TOTAL_ORDERS
FROM ORDERS 
GROUP BY MONTH
ORDER BY MONTH;



--CUSTOMER ANALYSIS


--TOP 10 CUSTOMERS BY SPENDING
SELECT C.CUSTOMER_ID, COUNT(DISTINCT O.ORDER_ID) AS NUMBER_OF_ORDERS, SUM(P.PAYMENT_VALUE) AS TOTAL_SPENDING
FROM PAYMENTS AS P
JOIN ORDERS AS O 
ON P.ORDER_ID=O.ORDER_ID
JOIN CUSTOMERS AS C
ON C.CUSTOMER_ID=O.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID
ORDER BY TOTAL_SPENDING DESC
LIMIT 10;


--CUSTOMERS WITH HIGHEST NUMBER OF ORDERS
SELECT C.CUSTOMER_ID,COUNT(O.ORDER_ID) AS NUMBER_OF_ORDERS
FROM CUSTOMERS AS C 
JOIN ORDERS AS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID
ORDER BY NUMBER_OF_ORDERS DESC;


--AVERAGE SPENDING PER CUSTOMER
SELECT C.CUSTOMER_ID, AVG(P.PAYMENT_VALUE) AS AVG_SPENDING
FROM ORDERS AS O
JOIN PAYMENTS AS P
ON O.ORDER_ID=P.ORDER_ID
JOIN CUSTOMERS AS C
ON C.CUSTOMER_ID=O.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID
ORDER BY AVG_SPENDING DESC;


--REPEAT CUSTOMERS
SELECT C.CUSTOMER_ID,COUNT(O.CUSTOMER_ID)-1 AS TIMES_REPEATED
FROM CUSTOMERS AS C 
JOIN ORDERS AS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID
HAVING TIMES_REPEATED>0
ORDER BY TIMES_REPEATED DESC;


--CUSTOMER DISTRIBUTION BY STATE
SELECT CUSTOMER_STATE,COUNT(*) AS NUMBER_OF_CUSTOMERS
FROM CUSTOMERS
GROUP BY CUSTOMER_STATE;


-- ====================================
--PRODUCT ANALYSIS
-- ====================================


--TOP SELLING PODUCTS
SELECT PR.PRODUCT_ID,PR.PRODUCT_CATEGORY_NAME,COUNT(OI.ORDER_ID) AS TIMES_ORDER_PURCHASED
FROM PRODUCTS AS PR
JOIN ORDER_ITEMS AS OI
ON PR.PRODUCT_ID=OI.PRODUCT_ID
GROUP BY PR.PRODUCT_ID,PR.PRODUCT_CATEGORY_NAME
ORDER BY TIMES_ORDER_PURCHASED DESC
LIMIT 10;


--HIGHEST REVENUE PRODUCTS
SELECT PR.PRODUCT_ID,PR.PRODUCT_CATEGORY_NAME,SUM(OI.PRICE) AS REVENUE
FROM PRODUCTS AS PR
JOIN ORDER_ITEMS AS OI
ON PR.PRODUCT_ID=OI.PRODUCT_ID
GROUP BY PR.PRODUCT_ID,PR.PRODUCT_CATEGORY_NAME
ORDER BY REVENUE DESC
LIMIT 10;


--TOP PRODUCT CATEGORIES
SELECT PR.PRODUCT_CATEGORY_NAME,SUM(OI.PRICE) AS REVENUE_FROM_CATEGORY
FROM PRODUCTS AS PR
JOIN ORDER_ITEMS AS OI
ON PR.PRODUCT_ID=OI.PRODUCT_ID
GROUP BY PR.PRODUCT_CATEGORY_NAME
ORDER BY REVENUE_FROM_CATEGORY DESC
LIMIT 10;


--CATEGORIES WITH HIGHEST REVENUE
SELECT PR.PRODUCT_CATEGORY_NAME,SUM(OI.PRICE) AS REVENUE_FROM_CATEGORY
FROM PRODUCTS AS PR
JOIN ORDER_ITEMS AS OI
ON PR.PRODUCT_ID=OI.PRODUCT_ID
GROUP BY PR.PRODUCT_CATEGORY_NAME
ORDER BY REVENUE_FROM_CATEGORY DESC
LIMIT 10;


--AVERAGE PRODUCT PRICE BY CATEGORY
SELECT PR.PRODUCT_CATEGORY_NAME,AVG(OI.PRICE) AS AVG_PRICE_BY_CATEGORY
FROM PRODUCTS AS PR
JOIN ORDER_ITEMS AS OI
ON PR.PRODUCT_ID=OI.PRODUCT_ID
GROUP BY PR.PRODUCT_CATEGORY_NAME;


-- ====================================
--SELLERS ANALYSIS
-- ====================================


--TOP SELLERS BY REVENUE
SELECT S.SELLER_ID,SUM(OI.PRICE) AS REVENUE_BY_SELLER
FROM SELLERS AS S
JOIN ORDER_ITEMS AS OI
ON S.SELLER_ID=OI.SELLER_ID
GROUP BY S.SELLER_ID
ORDER BY REVENUE_BY_SELLER DESC
LIMIT 10;


--TOP SELLERS BY ORDERS
SELECT S.SELLER_ID,COUNT(DISTINCT OI.ORDER_ID) AS ORDERS_BY_SELLER
FROM SELLERS AS S
JOIN ORDER_ITEMS AS OI
ON S.SELLER_ID=OI.SELLER_ID
GROUP BY S.SELLER_ID
ORDER BY ORDERS_BY_SELLER DESC
LIMIT 10;


--AVERAGE SELLER REVENUE
SELECT AVG(SELLER_REVENUE) AS AVG_SELLER_REVENUE 
FROM(SELECT SELLER_ID,SUM(PRICE) AS SELLER_REVENUE
	 FROM ORDER_ITEMS GROUP BY SELLER_ID)AS TEMP;


--SELLER DISTRIBUTION BY STATE
SELECT SELLER_STATE,COUNT(SELLER_ID) AS NUMBER_OF_SELLERS
FROM SELLERS
GROUP BY SELLER_STATE
ORDER BY NUMBER_OF_SELLERS DESC;



-- ====================================
--REVIEWS ANALYSIS
-- ====================================


--AVERAGE REVIEW SCORE
SELECT AVG(REVIEW_SCORE) FROM REVIEWS;


--REVIEW SCORE DISTRIBUTION
SELECT REVIEW_SCORE,COUNT(*) AS REVIEW_COUNT
FROM REVIEWS
GROUP BY REVIEW_SCORE
ORDER BY REVIEW_SCORE;


--REVENUE VS REVIEW SCORE
SELECT R.REVIEW_SCORE,SUM(P.PAYMENT_VALUE) AS REVENUE
FROM REVIEWS AS R
JOIN PAYMENTS AS P
ON R.ORDER_ID=P.ORDER_ID
GROUP BY R.REVIEW_SCORE
ORDER BY R.REVIEW_SCORE;


--CATEGORIES WITH LOWEST RATINGS
SELECT PR.PRODUCT_CATEGORY_NAME,AVG(R.REVIEW_SCORE) AS AVG_REVIEW_SCORE
FROM PRODUCTS AS PR
JOIN ORDER_ITEMS AS OI
ON PR.PRODUCT_ID=OI.PRODUCT_ID
JOIN REVIEWS AS R 
ON R.ORDER_ID=OI.ORDER_ID
GROUP BY PR.PRODUCT_CATEGORY_NAME
ORDER BY AVG_REVIEW_SCORE
LIMIT 10;



-- ====================================
--DELIVERY ANALYSIS
-- ====================================


--AVERAGE DELIVERY TIME
SELECT AVG(DATEDIFF(ORDER_DELIVERED_CUSTOMER_DATE,ORDER_PURCHASE_TIMESTAMP))
AS AVG_DELIVERY_DAYS FROM ORDERS;


--FASTEST DELIVERY STATES
SELECT C.CUSTOMER_STATE, AVG(DATEDIFF(O.ORDER_DELIVERED_CUSTOMER_DATE,O.ORDER_PURCHASE_TIMESTAMP))
AS NUMBER_OF_DELIVERY_DAYS 
FROM ORDERS AS O
JOIN CUSTOMERS AS C 
ON O.CUSTOMER_ID=C.CUSTOMER_ID
WHERE O.ORDER_DELIVERED_CUSTOMER_DATE IS NOT NULL
GROUP BY C.CUSTOMER_STATE
ORDER BY NUMBER_OF_DELIVERY_DAYS ASC
LIMIT 10;



--SLOWEST DELIVERY STATES
SELECT C.CUSTOMER_STATE, AVG(DATEDIFF(O.ORDER_DELIVERED_CUSTOMER_DATE,O.ORDER_PURCHASE_TIMESTAMP))
AS NUMBER_OF_DELIVERY_DAYS 
FROM ORDERS AS O
JOIN CUSTOMERS AS C 
ON O.CUSTOMER_ID=C.CUSTOMER_ID
WHERE O.ORDER_DELIVERED_CUSTOMER_DATE IS NOT NULL
GROUP BY C.CUSTOMER_STATE
ORDER BY NUMBER_OF_DELIVERY_DAYS DESC
LIMIT 10;


--ORDERS DELIVERED LATE
SELECT O.ORDER_ID FROM ORDERS AS O
WHERE O.ORDER_DELIVERED_CUSTOMER_DATE > O.ORDER_ESTIMATED_DELIVERY_DATE;


--DELIVERY DELAY DISTRIBUTION
SELECT DATEDIFF(O.ORDER_DELIVERED_CUSTOMER_DATE,O.ORDER_ESTIMATED_DELIVERY_DATE) AS DELAY_DAYS,
COUNT(*) AS NUMBER_OF_ORDERS
FROM ORDERS AS O
WHERE O.ORDER_DELIVERED_CUSTOMER_DATE IS NOT NULL
GROUP BY DELAY_DAYS
ORDER BY DELAY_DAYS DESC;
