CREATE DATABASE olist;
USE olist;



CREATE TABLE CUSTOMERS(
CUSTOMER_ID VARCHAR(50) PRIMARY KEY,
CUSTOMER_UNIQUE_ID VARCHAR(50),
CUSTOMER_ZIP_CODE_PREFIX INT,
CUSTOMER_CITY VARCHAR(100),
CUSTOMER_STATE VARCHAR(10)
);



CREATE TABLE ORDERS(
ORDER_ID VARCHAR(50) PRIMARY KEY,
CUSTOMER_ID VARCHAR (50),
ORDER_STATUS VARCHAR(20),
ORDER_PURCHASE_TIMESTAMP DATETIME,
ORDER_APPROVED_AT DATETIME,
ORDER_DELIVERED_CARRIER_DATE DATETIME,
ORDER_ESTIMATED_DELIVERY_DATE DATETIME,

FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);


CREATE TABLE REVIEWS(
REVIEW_PK INT AUTO_INCREMENT PRIMARY KEY,
REVIEW_ID VARCHAR(50),
ORDER_ID VARCHAR(50),
REVIEW_SCORE TINYINT,
REVIEW_COMMENT_TITLE TEXT,
REVIEW_COMMENT_MESSAGE TEXT,
REVIEW_CREATION_DATE DATETIME,
REVIEW_ANSWER_TIMESTAMP DATETIME,

FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID)
);




CREATE TABLE PAYMENTS(
ORDER_ID VARCHAR(50),
PAYMENT_SEQUENTIAL TINYINT,
PAYMENT_TYPE VARCHAR(20),
PAYMENT_INSTALLMENTS TINYINT,
PAYMENT_VALUE FLOAT,

PRIMARY KEY(ORDER_ID,PAYMENT_SEQUENTIAL),

FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID)
);


CREATE TABLE ORDER_ITEMS(
ORDER_ID VARCHAR(50),
ORDER_ITEM_ID TINYINT,
PRODUCT_ID VARCHAR(50),
SELLER_ID VARCHAR(50),
SHIPPING_LIMIT_DATE DATETIME,
PRICE FLOAT,
FREIGHT_VALUE FLOAT,

PRIMARY KEY (ORDER_ID, ORDER_ITEM_ID),

FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
FOREIGN KEY (SELLER_ID) REFERENCES SELLERS(SELLER_ID)
);


CREATE TABLE PRODUCTS(
PRODUCT_ID VARCHAR(50) PRIMARY KEY,
PRODUCT_CATEGORY_NAME VARCHAR(100),
PRODUCT_NAME_LENGTH TINYINT,
PRODUCT_DESCRIPTION_LENGTH INT,
PRODUCT_PHOTOS_QTY TINYINT,
PRODUCT_WEIGHT INT,
PRODUCT_LENGTH INT,
PRODUCT_HEIGHT INT,
PRODUCT_WIDTH INT
);


CREATE TABLE SELLERS(
SELLER_ID VARCHAR(50) PRIMARY KEY,
SELLER_ZIP_CODE_PREFIX INT,
SELLER_CITY VARCHAR(50),
SELLER_STATE VARCHAR(10)
);


CREATE TABLE GEOLOCATION(
GEOLOCATION_ZIP_CODE_PREFIX INT,
GEOLOCATION_LAT FLOAT,
GEOLOCATION_LNG FLOAT,
GEOLOCATION_CITY VARCHAR(50),
GEOLOCATION_STATE VARCHAR(10)
);





CREATE TABLE TRANSLATION(
PRODUCT_CATEGORY_NAME VARCHAR(50) PRIMARY KEY,
PRODUCT_CATEGORY_NAME_ENGLISH VARCHAR (50)
);



ALTER TABLE ORDERS
ADD COLUMN ORDER_DELIVERED_CUSTOMER_DATE DATETIME;





